service:
  name: Order
rest:
  host: 0.0.0.0
  port: 8081
  endpoints:
    - route: /orders
      method: POST
      controller: src.OrderController
      action: create_orders
      name: ""
    - route: /orders
      method: GET
      controller: src.OrderController
      action: get_orders
      name: ""
repository:
  database: order_db
  user: minos
  password: min0s
  host: localhost
  port: 5432
snapshot:
  database: order_db
  user: minos
  password: min0s
  host: localhost
  port: 5432
events:
  broker: localhost
  port: 9092
  queue:
    database: order_db
    user: minos
    password: min0s
    host: localhost
    port: 5432
    records: 10
    retry: 2
  items: []
commands:
  broker: localhost
  port: 9092
  items:
    - name: CreateProduct
      controller: src.OrderController
      action: create_order
    - name: GetProducts
      controller: src.OrderController
      action: get_orders
  queue:
    database: order_db
    user: minos
    password: min0s
    host: localhost
    port: 5432
    records: 10
    retry: 2
saga:
  broker: localhost
  port: 9092
  storage:
    path: "./order.lmdb"
  items: []
  queue:
    database: order_db
    user: minos
    password: min0s
    host: localhost
    port: 5432
    records: 10
    retry: 2
