service:
  name: orders
  injections:
    command_broker: minos.networks.CommandBroker
    command_reply_broker: minos.networks.CommandReplyBroker
    event_broker: minos.networks.EventBroker
    repository: minos.common.PostgreSqlRepository
    saga_manager: minos.saga.SagaManager
    snapshot: minos.common.PostgreSqlSnapshot
    discovery: minos.networks.DiscoveryConnector
  services:
    - minos.networks.CommandConsumerService
    - minos.networks.CommandHandlerService
    - minos.networks.CommandReplyConsumerService
    - minos.networks.CommandReplyHandlerService
    - minos.networks.EventConsumerService
    - minos.networks.EventHandlerService
    - minos.networks.RestService
    - minos.networks.SnapshotService
    - minos.networks.ProducerService
rest:
  host: 0.0.0.0
  port: 8082
  endpoints:
    - route: /orders
      method: POST
      controller: src.OrderCommandService
      action: create_order
      name: ""
    - route: /orders
      method: GET
      controller: src.OrderCommandService
      action: get_orders
      name: ""
repository:
  database: order_db
  user: minos
  password: min0s
  host: localhost
  port: 5432
snapshot:
  database: order_db
  user: minos
  password: min0s
  host: localhost
  port: 5432
events:
  broker: localhost
  port: 9092
  queue:
    database: order_db
    user: minos
    password: min0s
    host: localhost
    port: 5432
    records: 10
    retry: 2
  items:
    - name: OrderCreated
      controller: src.OrderQueryService
      action: order_created
    - name: OrderUpdated
      controller: src.OrderQueryService
      action: order_updated
    - name: OrderDeleted
      controller: src.OrderQueryService
      action: order_deleted
commands:
  broker: localhost
  port: 9092
  items:
    - name: CreateOrder
      controller: src.OrderCommandService
      action: create_order
  queue:
    database: order_db
    user: minos
    password: min0s
    host: localhost
    port: 5432
    records: 10
    retry: 2
saga:
  broker: localhost
  port: 9092
  storage:
    path: "./order.lmdb"
  items:
    - name: CreateOrder
      controller: src
      action: CREATE_ORDER
  queue:
    database: order_db
    user: minos
    password: min0s
    host: localhost
    port: 5432
    records: 10
    retry: 2
discovery:
  host: localhost
  port: 5567
  endpoints:
    subscribe:
      path: subscribe
      method: POST
    unsubscribe:
      path: unsubscribe
      method: POST
    discover:
      path: discover
      method: GET
