[tool.poetry]
name = "order"
version = "0.1.0"
description = ""
authors = ["Clariteia Devs <devs@clariteia.com>"]
packages = [{ include = "src" }]

[tool.poetry.dependencies]
python = "^3.9"
minos-microservice-common = { git = "https://github.com/clariteia/minos_microservice_common.git", rev = "98cdb0c9c75f554e4ff294e06910bacf5c03aa3b" }
minos-microservice-networks = { git = "https://github.com/clariteia/minos_microservice_networks.git", rev = "8b1a69e288cd6cb8bd97eaa069cc383a0f6e26e1" }
minos-microservice-saga = { git = "https://github.com/clariteia/minos_microservice_saga.git", rev = "58c319e17b23b14cdd0877d936fc0587d0326a8a" }
typer = "^0.3.2"

[tool.poetry.dev-dependencies]
pytest = "^6.2.4"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
microservice = "src.cli:main"