version: "3.9"

x-microservice-environment: &microservice-environment
  - PYTHONPATH=/microservice
  - MINOS_EVENTS_QUEUE_HOST=postgres
  - MINOS_EVENTS_BROKER=kafka
  - MINOS_COMMANDS_QUEUE_HOST=postgres
  - MINOS_COMMANDS_BROKER=kafka
  - MINOS_REPOSITORY_HOST=postgres
  - MINOS_SNAPSHOT_HOST=postgres
  - MINOS_SAGA_QUEUE_HOST=postgres
  - MINOS_SAGA_BROKER=kafka

x-microservice-depends-on: &microservice-depends-on
  - postgres
  - kafka
  - discovery

services:
  zookeeper:
    restart: always
    image: wurstmeister/zookeeper:latest
    logging:
      driver: none

  kafka:
    restart: always
    image: wurstmeister/kafka:latest
    depends_on:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    logging:
      driver: none

  postgres:
    restart: always
    build: external/postgres
    volumes:
      - postgres_volume:/var/lib/postgresql
    environment:
      - POSTGRES_MULTIPLE_DATABASES=inventory_db,order_db,payment_db,product_db,ticket_db
      - POSTGRES_USER=minos
      - POSTGRES_PASSWORD=min0s
    logging:
      driver: none

  redis:
    image: redis:latest
    command: "redis-server"
    logging:
      driver: none

  # FIXME: Configure tavern
  #  tavern:
  #    restart: always
  #    build: external/tavern

  api-gateway:
    restart: always
    build: ./api_gateway
    ports:
      - 5566:5566
    environment:
      - PYTHONPATH=/api_gateway
    depends_on:
      - discovery

  discovery:
    restart: always
    build: ./external/discovery
    environment:
      - DISCOVERY_SERVICE_DB_HOST=redis
    depends_on:
      - redis

  microservice-inventory:
    restart: always
    build: microservices/inventory
    environment: *microservice-environment
    depends_on: *microservice-depends-on

  microservice-order:
    restart: always
    build: microservices/order
    environment: *microservice-environment
    depends_on: *microservice-depends-on

  microservice-payment:
    restart: always
    build: microservices/payment
    environment: *microservice-environment
    depends_on: *microservice-depends-on

  microservice-product:
    restart: always
    build: microservices/product
    environment: *microservice-environment
    depends_on: *microservice-depends-on

  microservice-ticket:
    restart: always
    build: microservices/ticket
    environment: *microservice-environment
    depends_on: *microservice-depends-on

volumes:
  postgres_volume:
