version: "3.9"

x-microservice-environment: &microservice-environment
  - MINOS_BROKER_QUEUE_HOST=postgres
  - MINOS_BROKER_HOST=kafka
  - MINOS_REPOSITORY_HOST=postgres
  - MINOS_SNAPSHOT_HOST=postgres
  - MINOS_DISCOVERY_HOST=discovery

x-microservice-depends-on: &microservice-depends-on
  - postgres
  - kafka
  - discovery

services:
  zookeeper:
    restart: always
    image: wurstmeister/zookeeper:latest

  kafka:
    restart: always
    image: wurstmeister/kafka:latest
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

  postgres:
    restart: always
    build: external/postgres
    ports:
    - "5432:5432"
    volumes:
      - postgres_volume:/var/lib/postgresql
    environment:
      - POSTGRES_MULTIPLE_DATABASES=order_db,order_query_db,payment_db,product_db,ticket_db,customer_db,cart_query_db,ticket_query_db,product_query_db,payment_query_db,review_db,review_query_db,auth_db,auth_query_db,cart_db,cart_query_db
      - POSTGRES_USER=minos
      - POSTGRES_PASSWORD=min0s

  redis:
    image: redis:latest
    command: "redis-server"

  tavern:
    build: external/tavern
    profiles:
      - donotstart
    volumes:
      - ./external/tavern/:/tavern/:ro

  api-gateway:
    restart: always
    build: external/api_gateway
    ports:
      - "5566:5566"
    environment:
      - PYTHONPATH=/api_gateway
      - API_GATEWAY_DISCOVERY_HOST=discovery
      - API_GATEWAY_REST_AUTH_HOST=microservice-authentication
    depends_on:
      - discovery
      - microservice-authentication

  discovery:
    restart: always
    build: external/discovery
    ports:
      - "5567:5567"
    environment:
      - DISCOVERY_SERVICE_DB_HOST=redis
    depends_on:
      - redis

  microservice-authentication:
    restart: always
    build:
      context: microservices/authentication
      target: production
    environment: *microservice-environment
    depends_on: *microservice-depends-on

  microservice-order:
    restart: always
    build:
      context: microservices/order
      target: production
    environment: *microservice-environment
    depends_on: *microservice-depends-on

  microservice-payment:
    restart: always
    build:
      context: microservices/payment
      target: production
    environment: *microservice-environment
    depends_on: *microservice-depends-on

  microservice-product:
    restart: always
    build:
      context: microservices/product
      target: production
    environment: *microservice-environment
    depends_on: *microservice-depends-on

  microservice-ticket:
    restart: always
    build:
      context: microservices/ticket
      target: production
    environment: *microservice-environment
    depends_on: *microservice-depends-on

  microservice-customer:
    restart: always
    build:
      context: microservices/customer
      target: production
    environment: *microservice-environment
    depends_on: *microservice-depends-on

  microservice-review:
    restart: always
    build:
      context: microservices/review
      target: production
    environment: *microservice-environment
    depends_on: *microservice-depends-on

  microservice-cart:
    restart: always
    build:
      context: microservices/cart
      target: production
    environment: *microservice-environment
    depends_on: *microservice-depends-on

  frontend:
    restart: always
    build: external/front
    ports:
      - "3000:3000"
volumes:
  postgres_volume:
