version: "3.9"

services:
  microservice-order:
    build:
      context: microservices/order
      target: development
    volumes:
      - ./microservices/order:/microservice

  microservice-payment:
    build:
      context: microservices/payment
      target: development
    volumes:
      - ./microservices/payment:/microservice

  microservice-product:
    build:
      context: microservices/product
      target: development
    volumes:
      - ./microservices/product:/microservice

  microservice-ticket:
    build:
      context: microservices/ticket
      target: development
    volumes:
      - ./microservices/ticket:/microservice

  microservice-customer:
    build:
      context: microservices/customer
      target: development
    volumes:
      - ./microservices/customer:/microservice

  microservice-review:
    build:
      context: microservices/review
      target: development
    volumes:
      - ./microservices/review:/microservice