test_name: Test Discovery Service Rest API
includes:
  - !include ../includes.yaml

stages:
  - name: Make sure that the subscription is working properly

    request:
      url: "{discovery.protocol:s}://{discovery.host:s}:{discovery.port:d}/subscribe"
      json:
        ip: "microservice-test"
        port: 8081
        name: "test"
      method: POST

    response:
      status_code: 200
      #json:
      #  status: "Service added"

  - name: Make sure that the endpoint info returns right data

    request:
      url: "{discovery.protocol:s}://{discovery.host:s}:{discovery.port:d}/discover?name=test"
      method: GET

    response:
      status_code: 200
      json:
        ip: "microservice-test"
        port: 8081
        name: "test"
        status: true
        subscribed: true

  - name: Make sure that the unsubscription is working properly

    request:
      url: "{discovery.protocol:s}://{discovery.host:s}:{discovery.port:d}/unsubscribe?name=test"
      method: POST

    response:
      status_code: 200
      #json:
      #  status: "Unsubscription done!"

  - name: Make sure that the unsubscription was done

    request:
      url: "{discovery.protocol:s}://{discovery.host:s}:{discovery.port:d}/discover?name=test"
      method: GET

    response:
      status_code: 200
      json:
        ip: "microservice-test"
        port: 8081
        name: "test"
        status: true
        subscribed: false