service:
    name: Shipment
rest:
    host: 0.0.0.0
    port: 8082
    endpoints:
        -   route: /shipments
            method: POST
            controller: src.ShipmentController
            action: create_shipment
            name: ""
        -   route: /shipments
            method: GET
            controller: src.ShipmentController
            action: get_shipments
            name: ""
repository:
    database: shipment_db
    user: minos
    password: min0s
    host: localhost
    port: 5432
snapshot:
    database: shipment_db
    user: minos
    password: min0s
    host: localhost
    port: 5432
events:
    broker: localhost
    port: 9092
    queue:
        database: shipment_db
        user: minos
        password: min0s
        host: localhost
        port: 5432
        records: 10
        retry: 2
    items: []
commands:
    broker: localhost
    port: 9092
    items:
        -   name: CreateShipment
            controller: src.ShipmentController
            action: create_shipment
    queue:
        database: shipment_db
        user: minos
        password: min0s
        host: localhost
        port: 5432
        records: 10
        retry: 2
saga:
    broker: localhost
    port: 9092
    storage:
        path: "./shipment.lmdb"
    items:
        -   name: CreateShipment
            controller: src.sagas
            action: CREATE_SHIPMENT
    queue:
        database: shipment_db
        user: minos
        password: min0s
        host: localhost
        port: 5432
        records: 10
        retry: 2
