rest:
  host: 0.0.0.0
  port: 5566
  endpoints:

    - name: AddInventory
      route: /inventories
      method: POST
      controller: minos.api_gateway.rest.DefaultController
      action: default

    - name: GetInventories
      route: /inventories
      method: GET
      controller: minos.api_gateway.rest.DefaultController
      action: default

    - name: AddOrder
      route: /orders
      method: POST
      controller: minos.api_gateway.rest.DefaultController
      action: default

    - name: GetOrders
      route: /orders
      method: GET
      controller: minos.api_gateway.rest.DefaultController
      action: default

    - name: AddPayment
      route: /payments
      method: POST
      controller: minos.api_gateway.rest.DefaultController
      action: default

    - name: GetPayments
      route: /payments
      method: GET
      controller: minos.api_gateway.rest.DefaultController
      action: default

    - name: AddProduct
      route: /products
      method: POST
      controller: minos.api_gateway.rest.DefaultController
      action: default

    - name: GetProducts
      route: /products
      method: GET
      controller: minos.api_gateway.rest.DefaultController
      action: default

    - name: AddTicket
      route: /tickets
      method: POST
      controller: minos.api_gateway.rest.DefaultController
      action: default

    - name: GetTickets
      route: /tickets
      method: GET
      controller: minos.api_gateway.rest.DefaultController
      action: default

discovery:
  host: localhost
  port: 5567
  path: /discover
  endpoints: []
  db:
    host: localhost
    port: 6379
    password:
