rest:
  host: 0.0.0.0
  port: 5566
  endpoints:
    - name: GetOrder
      route: /orders/{id}
      method: GET
      controller: src.OrderController
      action: get
    - name: AddOrder
      route: /orders
      method: POST
      controller: src.OrderController
      action: add
    - name: History
      route: /orders/{id}/history
      method: GET
      controller: src.OrderController
      action: history
    - name: GetProduct
      route: /products/{id}
      method: GET
      controller: src.ProductController
      action: get
    - name: AddOrder
      route: /products
      method: POST
      controller: src.ProductController
      action: add
    - name: AllProducts
      route: /products
      method: GET
      controller: src.ProductController
      action: all_products
discovery:
  host: discovery
  port: 8080
  path: discover
  endpoints:
    - name: Discover
      route: /discover
      method: GET
      controller: minos.api_gateway.discovery.handlers.DiscoveryHandlers
      action: discover
    - name: Subscribe
      route: /subscribe
      method: POST
      controller: minos.api_gateway.discovery.handlers.DiscoveryHandlers
      action: subscribe
    - name: Unsubscribe
      route: /unsubscribe
      method: POST
      controller: minos.api_gateway.discovery.handlers.DiscoveryHandlers
      action: unsubscribe
    - name: SystemHealth
      route: /system/health
      method: GET
      controller: minos.api_gateway.discovery.handlers.DiscoveryHandlers
      action: system_health
  db:
    host: localhost
    port: 6379
    password:
