[tool.poetry]
name = "api_gateway"
version = "0.1.0"
description = ""
authors = ["vladyslav-fenchak <vladyslav.fenchak@clariteia.com>"]

[tool.poetry.dependencies]
python = "^3.9"
minos-apigateway = "^0.0.1"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

