rest:
  host: 0.0.0.0
  port: 5566
  cors:
    enabled: true
  auth:
      enabled: true
      host: localhost
      port: 8089
      method: POST
      path: /token
discovery:
  host: localhost
  port: 5567