version: 2
name: product
injections:
  - src.ProductQueryRepository
databases:
  default:
    client: minos.plugins.aiopg.AiopgDatabaseClient
    database: product_db
    user: minos
    password: min0s
    host: localhost
    port: 5432
  snapshot:
    client: minos.plugins.sqlalchemy.SqlAlchemyDatabaseClient
    driver: postgresql+asyncpg
    database: product_db
    user: minos
    password: min0s
    host: localhost
    port: 5432
interfaces:
  broker:
    port: minos.networks.BrokerPort
    common:
      host: localhost
      port: 9092
    publisher:
      client: minos.plugins.kafka.KafkaBrokerPublisher
      queue: minos.networks.DatabaseBrokerPublisherQueue
    subscriber:
      client: minos.plugins.kafka.KafkaBrokerSubscriber
      queue: minos.networks.DatabaseBrokerSubscriberQueue
      validator: minos.networks.DatabaseBrokerSubscriberDuplicateValidator
  http:
    port: minos.networks.HttpPort
    connector:
      client: minos.plugins.aiohttp.AioHttpConnector
      port: 8084
  periodic:
    port: minos.networks.PeriodicPort
discovery:
  connector: minos.networks.DiscoveryConnector
  client: minos.plugins.minos_discovery.MinosDiscoveryClient
pools:
  lock: minos.common.DatabaseLockPool
  database: minos.common.DatabaseClientPool
  broker: minos.networks.BrokerClientPool
saga:
  manager: minos.saga.SagaManager
aggregate:
  client: src.aggregates.ProductAggregate
  publisher:
    client: minos.networks.TransactionalBrokerPublisher
    repository: minos.networks.DatabaseBrokerPublisherTransactionRepository
  entities:
    - src.aggregates.Product
  repositories:
    transaction: minos.transactions.DatabaseTransactionRepository
    event: minos.aggregate.DatabaseDeltaRepository
    snapshot: minos.plugins.sqlalchemy.SqlAlchemySnapshotRepository
routers:
  - minos.networks.BrokerRouter
  - minos.networks.PeriodicRouter
  - minos.networks.RestHttpRouter
middleware:
  - minos.saga.transactional_command
services:
  - minos.networks.SystemService
  - minos.aggregate.SnapshotService
  - minos.saga.SagaService
  - src.ProductQueryService
  - src.ProductCommandService
