service:
    name: products
    injections:
        command_broker: minos.networks.CommandBroker
        command_reply_broker: minos.networks.CommandReplyBroker
        event_broker: minos.networks.EventBroker
        repository: minos.common.PostgreSqlRepository
        saga_manager: minos.saga.SagaManager
        snapshot: minos.common.PostgreSqlSnapshot
        discovery: minos.networks.DiscoveryConnector
    services:
        - minos.networks.CommandConsumerService
        - minos.networks.CommandHandlerService
        - minos.networks.CommandReplyConsumerService
        - minos.networks.CommandReplyHandlerService
        - minos.networks.EventConsumerService
        - minos.networks.EventHandlerService
        - minos.networks.RestService
        - minos.networks.SnapshotService
        - minos.networks.ProducerService
rest:
    host: 0.0.0.0
    port: 8084
    endpoints:
        -   route: /products
            method: POST
            controller: src.ProductController
            action: create_product
            name: ""

        -   route: /products/{uuid}/inventory
            method: PUT
            controller: src.ProductController
            action: update_inventory
            name: ""

        -   route: /products/{uuid}/inventory
            method: PATCH
            controller: src.ProductController
            action: update_inventory_diff
            name: ""

        -   route: /products
            method: GET
            controller: src.ProductController
            action: get_products
            name: ""

        -   route: /products/{uuid}
            method: DELETE
            controller: src.ProductController
            action: delete_product
            name: ""

repository:
    database: product_db
    user: minos
    password: min0s
    host: localhost
    port: 5432
snapshot:
    database: product_db
    user: minos
    password: min0s
    host: localhost
    port: 5432
events:
    broker: localhost
    port: 9092
    queue:
        database: product_db
        user: minos
        password: min0s
        host: localhost
        port: 5432
        records: 10
        retry: 2
    items: []
commands:
    broker: localhost
    port: 9092
    items:
        -   name: CreateProduct
            controller: src.ProductController
            action: create_product
        -   name: GetProducts
            controller: src.ProductController
            action: get_products
        -   name: ReserveProducts
            controller: src.ProductController
            action: reserve_products
    queue:
        database: product_db
        user: minos
        password: min0s
        host: localhost
        port: 5432
        records: 10
        retry: 2
saga:
    broker: localhost
    port: 9092
    storage:
        path: "./product.lmdb"
    items: []
    queue:
        database: product_db
        user: minos
        password: min0s
        host: localhost
        port: 5432
        records: 10
        retry: 2
discovery:
  host: localhost
  port: 5567
  endpoints:
    subscribe:
      path: subscribe
      method: POST
    unsubscribe:
      path: unsubscribe
      method: POST
    discover:
      path: discover
      method: GET
