version: 2
name: product
injections:
  - src.ProductQueryRepository
databases:
  default:
    client: minos.common.AiopgDatabaseClient
    database: product_db
  saga:
    path: "./product.lmdb"
interfaces:
  broker:
    port: minos.networks.BrokerPort
    common:
      host: localhost
      port: 9092
    publisher:
      client: minos.plugins.kafka.KafkaBrokerPublisher
      queue: minos.networks.DatabaseBrokerPublisherQueue
    subscriber:
      client: minos.plugins.kafka.KafkaBrokerSubscriber
      queue: minos.networks.DatabaseBrokerSubscriberQueue
      validator: minos.networks.DatabaseBrokerSubscriberDuplicateValidator
  http:
    port: minos.networks.HttpPort
    connector:
      client: minos.plugins.aiohttp.AioHttpConnector
      port: 8084
  periodic:
    port: minos.networks.PeriodicPort
pools:
  lock: minos.common.DatabaseLockPool
  database: minos.common.DatabaseClientPool
  broker: minos.networks.BrokerClientPool
saga:
  manager: minos.saga.SagaManager
aggregate:
  entities:
    - src.aggregates.Product
  repositories:
    transaction: minos.aggregate.DatabaseTransactionRepository
    event: minos.aggregate.DatabaseEventRepository
    snapshot: minos.aggregate.DatabaseSnapshotRepository
routers:
  - minos.networks.BrokerRouter
  - minos.networks.PeriodicRouter
  - minos.networks.RestHttpRouter
middleware:
  - minos.saga.transactional_command
services:
  - minos.networks.SystemService
  - minos.aggregate.TransactionService
  - minos.aggregate.SnapshotService
  - minos.saga.SagaService
  - src.ProductQueryService
  - src.ProductCommandService
