service:
  name: review
  aggregate: src.aggregates.Review
  injections:
    postgresql_pool: minos.common.PostgreSqlPool
    command_broker: minos.networks.CommandBroker
    command_reply_broker: minos.networks.CommandReplyBroker
    event_broker: minos.networks.EventBroker
    consumer: minos.networks.Consumer
    dynamic_handler_pool: minos.networks.DynamicHandlerPool
    repository: minos.common.PostgreSqlRepository
    saga_manager: minos.saga.SagaManager
    snapshot: minos.common.PostgreSqlSnapshot
    discovery: minos.networks.DiscoveryConnector
    review_repository: src.ReviewQueryRepository
  services:
    - minos.networks.CommandHandlerService
    - minos.networks.CommandReplyHandlerService
    - minos.networks.EventHandlerService
    - minos.networks.RestService
    - minos.networks.SnapshotService
    - minos.networks.ConsumerService
    - minos.networks.ProducerService
    - minos.networks.PeriodicTaskSchedulerService
rest:
  host: 0.0.0.0
  port: 8087
broker:
  host: localhost
  port: 9092
  queue:
    database: review_db
    user: minos
    password: min0s
    host: localhost
    port: 5432
    records: 1000
    retry: 2
repository:
  database: review_db
  user: minos
  password: min0s
  host: localhost
  port: 5432
snapshot:
  database: review_db
  user: minos
  password: min0s
  host: localhost
  port: 5432
commands:
  service: src.ReviewCommandService
queries:
  service: src.ReviewQueryService
saga:
  storage:
    path: "./review.lmdb"
discovery:
  client: minos.networks.MinosDiscoveryClient
  host: localhost
  port: 5567