service:
  name: review
  aggregate: src.aggregates.Review
  injections:
    http_connector: minos.plugins.aiohttp.AioHttpConnector
    lock_pool: minos.common.PostgreSqlLockPool
    postgresql_pool: minos.common.PostgreSqlPool
    broker_publisher: minos.plugins.kafka.PostgreSqlQueuedKafkaBrokerPublisher
    broker_subscriber_builder: minos.plugins.kafka.PostgreSqlQueuedKafkaBrokerSubscriberBuilder
    broker_pool: minos.networks.BrokerClientPool
    transaction_repository: minos.aggregate.PostgreSqlTransactionRepository
    event_repository: minos.aggregate.PostgreSqlEventRepository
    snapshot_repository: minos.aggregate.PostgreSqlSnapshotRepository
    saga_manager: minos.saga.SagaManager
    discovery: minos.networks.DiscoveryConnector
    review_repository: src.ReviewQueryRepository
  services:
    - minos.networks.BrokerHandlerPort
    - minos.networks.HttpPort
    - minos.networks.PeriodicTaskSchedulerPort
routers:
  - minos.networks.BrokerRouter
  - minos.networks.PeriodicRouter
  - minos.networks.RestHttpRouter
middleware:
  - minos.saga.transactional_command
services:
  - minos.networks.SystemService
  - minos.aggregate.TransactionService
  - minos.aggregate.SnapshotService
  - minos.saga.SagaService
  - src.ReviewCommandService
  - src.ReviewQueryService
rest:
  host: 0.0.0.0
  port: 8087
broker:
  host: localhost
  port: 9092
  queue:
    database: review_db
    user: minos
    password: min0s
    host: localhost
    port: 5432
    records: 1000
    retry: 2
repository:
  database: review_db
  user: minos
  password: min0s
  host: localhost
  port: 5432
snapshot:
  database: review_db
  user: minos
  password: min0s
  host: localhost
  port: 5432
saga:
  storage:
    path: "./review.lmdb"
discovery:
  client: minos.plugins.minos_discovery.MinosDiscoveryClient
  host: localhost
  port: 5567