service:
  name: review
  aggregate: src.aggregates.Review
  injections:
    http_connector: minos.plugins.aiohttp.AioHttpConnector
    lock_pool: minos.common.DatabaseLockPool
    database_pool: minos.common.DatabaseClientPool
    broker_publisher: minos.plugins.kafka.KafkaBrokerPublisher
    broker_subscriber_builder: minos.plugins.kafka.KafkaBrokerSubscriberBuilder
    broker_pool: minos.networks.BrokerClientPool
    transaction_repository: minos.transactions.DatabaseTransactionRepository
    event_repository: minos.aggregate.DatabaseEventRepository
    snapshot_repository: minos.aggregate.DatabaseSnapshotRepository
    saga_manager: minos.saga.SagaManager
    discovery: minos.networks.DiscoveryConnector
    review_repository: src.ReviewQueryRepository
  services:
    - minos.networks.BrokerPort
    - minos.networks.HttpPort
    - minos.networks.PeriodicPort
routers:
  - minos.networks.BrokerRouter
  - minos.networks.PeriodicRouter
  - minos.networks.RestHttpRouter
middleware:
  - minos.saga.transactional_command
services:
  - minos.networks.SystemService
  - minos.aggregate.SnapshotService
  - minos.saga.SagaService
  - src.ReviewCommandService
  - src.ReviewQueryService
rest:
  host: 0.0.0.0
  port: 8087
broker:
  queue:
    client: minos.plugins.aiopg.AiopgDatabaseClient
    database: review_db
    user: minos
    password: min0s
    host: localhost
    port: 5432
    records: 1000
    retry: 2
repository:
  client: minos.plugins.aiopg.AiopgDatabaseClient
  database: review_db
  user: minos
  password: min0s
  host: localhost
  port: 5432
snapshot:
  client: minos.plugins.aiopg.AiopgDatabaseClient
  database: review_db
  user: minos
  password: min0s
  host: localhost
  port: 5432
saga:
  storage:
    client: minos.plugins.lmdb.LmdbDatabaseClient
    path: "./review.lmdb"
discovery:
  client: minos.plugins.minos_discovery.MinosDiscoveryClient
  host: localhost
  port: 5567