service:
  name: payments
  injections:
    command_broker: minos.networks.CommandBroker
    command_reply_broker: minos.networks.CommandReplyBroker
    event_broker: minos.networks.EventBroker
    repository: minos.common.PostgreSqlRepository
    saga_manager: minos.saga.SagaManager
    snapshot: minos.common.PostgreSqlSnapshot
    discovery: minos.networks.DiscoveryConnector
  services:
    - minos.networks.CommandConsumerService
    - minos.networks.CommandHandlerService
    - minos.networks.CommandReplyConsumerService
    - minos.networks.CommandReplyHandlerService
    - minos.networks.EventConsumerService
    - minos.networks.EventHandlerService
    - minos.networks.RestService
    - minos.networks.SnapshotService
    - minos.networks.ProducerService
rest:
  host: 0.0.0.0
  port: 8083
  endpoints:
    - route: /payments
      method: POST
      controller: src.PaymentController
      action: create_payment
      name: ""
    - route: /payments
      method: GET
      controller: src.PaymentController
      action: get_payments
      name: ""
repository:
  database: payment_db
  user: minos
  password: min0s
  host: localhost
  port: 5432
snapshot:
  database: payment_db
  user: minos
  password: min0s
  host: localhost
  port: 5432
events:
  broker: localhost
  port: 9092
  queue:
    database: payment_db
    user: minos
    password: min0s
    host: localhost
    port: 5432
    records: 10
    retry: 2
  items: []
commands:
  broker: localhost
  port: 9092
  items:
    - name: CreatePayment
      controller: src.PaymentController
      action: create_payment
    - name: GetPayments
      controller: src.PaymentController
      action: get_payments
  queue:
    database: payment_db
    user: minos
    password: min0s
    host: localhost
    port: 5432
    records: 10
    retry: 2
saga:
  broker: localhost
  port: 9092
  storage:
    path: "./payment.lmdb"
  items: []
  queue:
    database: payment_db
    user: minos
    password: min0s
    host: localhost
    port: 5432
    records: 10
    retry: 2
discovery:
  host: discovery
  port: 8080
  endpoints:
    subscribe:
      path: subscribe
      method: POST
    unsubscribe:
      path: unsubscribe
      method: POST
    discover:
      path: discover
      method: GET
