service:
  name: Payment
rest:
  host: 0.0.0.0
  port: 8081
  endpoints:
    - route: /payments
      method: POST
      controller: src.payment.PaymentController
      action: create_payment
      name: ""
    - route: /payments
      method: GET
      controller: src.payment.PaymentController
      action: get_payments
      name: ""
repository:
  database: payment_db
  user: minos
  password: min0s
  host: localhost
  port: 5432
snapshot:
  database: payment_db
  user: minos
  password: min0s
  host: localhost
  port: 5432
events:
  broker: localhost
  port: 9092
  queue:
    database: payment_db
    user: minos
    password: min0s
    host: localhost
    port: 5432
    records: 10
    retry: 2
  items: []
commands:
  broker: localhost
  port: 9092
  items:
    - name: CreatePayment
      controller: src.payment.PaymentController
      action: create_payment
    - name: GetPayments
      controller: src.payment.PaymentController
      action: get_payments
  queue:
    database: payment_db
    user: minos
    password: min0s
    host: localhost
    port: 5432
    records: 10
    retry: 2
saga:
  broker: localhost
  port: 9092
  storage:
    path: "./payment.lmdb"
  items: []
  queue:
    database: payment_db
    user: minos
    password: min0s
    host: localhost
    port: 5432
    records: 10
    retry: 2
