[tool.poetry]
name = "payment"
version = "0.1.0"
description = ""
authors = ["Clariteia Devs <devs@clariteia.com>"]
packages = [{ include = "src" }]

[tool.poetry.dependencies]
python = "^3.9"
minos-microservice-common = { git = "https://github.com/clariteia/minos_microservice_common.git", rev = "e791de98483a1b393d6eb055b086cb62d67d07ec" }
minos-microservice-networks = "^0.0"
minos-microservice-saga = "^0.0"
typer = "^0.3.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
microservice = "src.cli:main"