version: 2
name: authentication
aggregate:
  client: src.aggregates.CredentialsAggregate
  publisher:
    client: minos.networks.TransactionalBrokerPublisher
    repository: minos.networks.DatabaseBrokerPublisherTransactionRepository
  entities:
    - src.aggregates.Credentials
  repositories:
    transaction: minos.transactions.DatabaseTransactionRepository
    event: minos.aggregate.DatabaseEventRepository
    snapshot: minos.aggregate.DatabaseSnapshotRepository
pools:
  lock: minos.common.DatabaseLockPool
  database: minos.common.DatabaseClientPool
  broker: minos.networks.BrokerClientPool
injections:
  - src.CredentialsQueryRepository
interfaces:
  broker:
    port: minos.networks.BrokerPort
    publisher:
      client: minos.plugins.kafka.KafkaBrokerPublisher
      queue: minos.networks.DatabaseBrokerPublisherQueue
    subscriber:
      client: minos.plugins.kafka.KafkaBrokerSubscriber
      queue: minos.networks.DatabaseBrokerSubscriberQueue
  http:
    port: minos.networks.HttpPort
    connector:
      client: minos.plugins.aiohttp.AioHttpConnector
      port: 8089
  periodic:
    port: minos.networks.PeriodicPort
routers:
  - minos.networks.BrokerRouter
  - minos.networks.PeriodicRouter
  - minos.networks.RestHttpRouter
middleware:
  - minos.saga.transactional_command
services:
  - minos.networks.SystemService
  - minos.aggregate.SnapshotService
  - minos.saga.SagaService
  - src.CredentialsQueryService
  - src.CredentialsCommandService
databases:
  default:
    client: minos.plugins.aiopg.AiopgDatabaseClient
    database: auth_db
    user: minos
    password: min0s
    host: localhost
    port: 5432
  saga:
    client: minos.plugins.lmdb.LmdbDatabaseClient
saga:
  manager: minos.saga.SagaManager
discovery:
  connector: minos.networks.DiscoveryConnector
  client: minos.plugins.minos_discovery.MinosDiscoveryClient
  host: localhost
  port: 5567
