service:
  name: ticket
  aggregate: src.aggregates.Ticket
  injections:
    postgresql_pool: minos.common.PostgreSqlPool
    command_broker: minos.networks.CommandBroker
    command_reply_broker: minos.networks.CommandReplyBroker
    event_broker: minos.networks.EventBroker
    consumer: minos.networks.Consumer
    dynamic_handler_pool: minos.networks.DynamicHandlerPool
    repository: minos.common.PostgreSqlRepository
    saga_manager: minos.saga.SagaManager
    snapshot: minos.common.PostgreSqlSnapshot
    discovery: minos.networks.DiscoveryConnector
    ticket_repository: src.TicketQueryRepository
  services:
    - minos.networks.CommandHandlerService
    - minos.networks.CommandReplyHandlerService
    - minos.networks.EventHandlerService
    - minos.networks.RestService
    - minos.networks.SnapshotService
    - minos.networks.ConsumerService
    - minos.networks.ProducerService
rest:
  host: 0.0.0.0
  port: 8085
broker:
  host: localhost
  port: 9092
  queue:
    database: ticket_db
    user: minos
    password: min0s
    host: localhost
    port: 5432
    records: 1000
    retry: 2
repository:
  database: ticket_db
  user: minos
  password: min0s
  host: localhost
  port: 5432
snapshot:
  database: ticket_db
  user: minos
  password: min0s
  host: localhost
  port: 5432
events:
  service: src.TicketQueryService
queries:
  service: src.TicketQueryService
commands:
  service: src.TicketCommandService
saga:
  storage:
    path: "./ticket.lmdb"
discovery:
  host: localhost
  port: 5567
  endpoints:
    subscribe:
      path: subscribe
      method: POST
    unsubscribe:
      path: unsubscribe
      method: POST
    discover:
      path: discover
      method: GET
