service:
  name: tickets
rest:
  host: 0.0.0.0
  port: 8082
  endpoints:
    - route: /tickets
      method: POST
      controller: src.TicketController
      action: create_ticket
      name: ""
    - route: /tickets
      method: GET
      controller: src.TicketController
      action: get_tickets
      name: ""
repository:
  database: ticket_db
  user: minos
  password: min0s
  host: localhost
  port: 5432
snapshot:
  database: ticket_db
  user: minos
  password: min0s
  host: localhost
  port: 5432
events:
  broker: localhost
  port: 9092
  queue:
    database: ticket_db
    user: minos
    password: min0s
    host: localhost
    port: 5432
    records: 10
    retry: 2
  items: []
commands:
  broker: localhost
  port: 9092
  items:
    - name: CreateTicket
      controller: src.TicketController
      action: create_ticket
    - name: GetTickets
      controller: src.TicketController
      action: get_tickets
  queue:
    database: ticket_db
    user: minos
    password: min0s
    host: localhost
    port: 5432
    records: 10
    retry: 2
saga:
  broker: localhost
  port: 9092
  storage:
    path: "./ticket.lmdb"
  items: []
  queue:
    database: ticket_db
    user: minos
    password: min0s
    host: localhost
    port: 5432
    records: 10
    retry: 2
discovery:
  host: discovery
  port: 8080
  endpoints:
    subscribe:
      path: subscribe
      method: POST
    unsubscribe:
      path: unsubscribe
      method: POST
    discover:
      path: discover
      method: GET
