service:
  name: ticket
  aggregate: src.aggregates.Ticket
  injections:
    lock_pool: minos.common.PostgreSqlLockPool
    postgresql_pool: minos.common.PostgreSqlPool
    command_broker: minos.networks.CommandBroker
    command_reply_broker: minos.networks.CommandReplyBroker
    event_broker: minos.networks.EventBroker
    consumer: minos.networks.Consumer
    dynamic_handler_pool: minos.networks.DynamicHandlerPool
    transaction_repository: minos.aggregate.PostgreSqlTransactionRepository
    event_repository: minos.aggregate.PostgreSqlEventRepository
    snapshot_repository: minos.aggregate.PostgreSqlSnapshotRepository
    saga_manager: minos.saga.SagaManager
    discovery: minos.networks.DiscoveryConnector
    ticket_repository: src.TicketQueryRepository
  services:
    - minos.networks.ProducerService
    - minos.networks.ConsumerService
    - minos.networks.RestService
    - minos.networks.CommandHandlerService
    - minos.networks.EventHandlerService
    - minos.networks.PeriodicTaskSchedulerService
middleware:
  - minos.saga.transactional_command
services:
  - minos.aggregate.TransactionService
  - minos.aggregate.SnapshotService
  - minos.saga.SagaService
  - src.TicketQueryService
  - src.TicketCommandService
rest:
  host: 0.0.0.0
  port: 8085
broker:
  host: localhost
  port: 9092
  queue:
    database: ticket_db
    user: minos
    password: min0s
    host: localhost
    port: 5432
    records: 1000
    retry: 2
repository:
  database: ticket_db
  user: minos
  password: min0s
  host: localhost
  port: 5432
snapshot:
  database: ticket_db
  user: minos
  password: min0s
  host: localhost
  port: 5432
saga:
  storage:
    path: "./ticket.lmdb"
discovery:
  client: minos.networks.MinosDiscoveryClient
  host: localhost
  port: 5567
