service:
  name: cart
  aggregate: src.aggregates.Cart
  injections:
    lock_pool: minos.common.PostgreSqlLockPool
    postgresql_pool: minos.common.PostgreSqlPool
    command_broker: minos.networks.CommandBroker
    command_reply_broker: minos.networks.CommandReplyBroker
    event_broker: minos.networks.EventBroker
    consumer: minos.networks.Consumer
    dynamic_handler_pool: minos.networks.DynamicHandlerPool
    transaction_repository: minos.aggregate.PostgreSqlTransactionRepository
    event_repository: minos.aggregate.PostgreSqlEventRepository
    snapshot_repository: minos.aggregate.PostgreSqlSnapshotRepository
    saga_manager: minos.saga.SagaManager
    discovery: minos.networks.DiscoveryConnector
    cart_repository: src.CartQueryRepository
  services:
    - minos.networks.ConsumerService
    - minos.networks.CommandHandlerService
    - minos.networks.CommandReplyHandlerService
    - minos.networks.EventHandlerService
    - minos.networks.RestService
    - minos.networks.SnapshotService
    - minos.networks.ProducerService
    - minos.networks.PeriodicTaskSchedulerService
rest:
  host: 0.0.0.0
  port: 8088
broker:
  host: localhost
  port: 9092
  queue:
    database: cart_db
    user: minos
    password: min0s
    host: localhost
    port: 5432
    records: 1000
    retry: 2
repository:
  database: cart_db
  user: minos
  password: min0s
  host: localhost
  port: 5432
snapshot:
  database: cart_db
  user: minos
  password: min0s
  host: localhost
  port: 5432
commands:
  service: src.CartCommandService
queries:
  service: src.CartQueryService
saga:
  storage:
    path: "./cart.lmdb"
discovery:
  client: minos.networks.MinosDiscoveryClient
  host: localhost
  port: 5567