name: Unit Tests - Product

on:
  push:
    paths:
      - 'microservices/product/**'
  pull_request:
    paths:
      - 'microservices/product/**'

jobs:
  build:
    runs-on: ubuntu-latest
    container: python:3.9-buster
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: product_db
          POSTGRES_USER: minos
          POSTGRES_PASSWORD: min0s
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

      zookeeper:
        image: wurstmeister/zookeeper:latest
        ports:
          - 2181:2181

      kafka:
        image: wurstmeister/kafka:latest
        ports:
          - 9092:9092
        env:
          KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
          KAFKA_ADVERTISED_HOST_NAME: kafka
    defaults:
      run:
        working-directory: ./microservices/product

    env:
      MINOS_EVENTS_QUEUE_HOST: postgres
      MINOS_EVENTS_BROKER: kafka
      MINOS_COMMANDS_QUEUE_HOST: postgres
      MINOS_COMMANDS_BROKER: kafka
      MINOS_REPOSITORY_HOST: postgres
      MINOS_SNAPSHOT_HOST: postgres
      MINOS_SAGA_QUEUE_HOST: postgres

    steps:
      - name: Skip if already running
        uses: fkirc/skip-duplicate-actions

      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Install Poetry
        uses: snok/install-poetry@v1.1.4

      - name: Install dependencies
        run: poetry install

      - name: Run tests
        run: poetry run pytest
